version: "3.8"
services:
  postgresql:
    image: postgres:15-alpine
    container_name: postgresql-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=your_password
    networks:
      - app-network
    restart: unless-stopped

  auth-service-app:
    container_name: auth-service-app
    user: root
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/usr/app/src
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_PROVIDER}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${DB_SCHEMA}

    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - redis
      - postgresql

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
